language: C
sudo: false

addons:
  apt:
    packages:
      - cabal-install-1.22
      - ghc-7.10.3
    sources:
      - hvr-ghc

cache:
  directories:
    - $HOME/.cabal/
    - $HOME/.ghc/
    - $HOME/.agda/

install:
  - export PATH=$HOME/.cabal/bin:/opt/ghc/7.10.3/bin:/opt/cabal/1.22/bin:$PATH;
  - cd travis/
  - ./install_agda.sh

script:
  - cd ../src/
  - agda linear/README.agda
