language: C
sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - cabal-install-2.0
      - ghc-8.2.2
    sources:
      - hvr-ghc

cache:
  directories:
    - $HOME/.cabal/
    - $HOME/.ghc/
    - $HOME/.agda/

install:
  - export PATH=$HOME/.cabal/bin:/opt/ghc/8.2.2/bin:/opt/cabal/2.0/bin:$PATH
  - cd travis/
  - travis_wait ./install_agda.sh

script:
  - cd ../src/
  - agda --html linear/README.agda
  - cd ../
  - mv src/html/* .

after_success:
  # uploading to gh-pages
  - git init
  - git config --global user.name "Travis CI bot"
  - git config --global user.email "travis-ci-bot@travis.fake"
  - git remote add upstream https://$GH_TOKEN@github.com/gallais/typing-with-leftover.git &>/dev/null
  - git fetch upstream && git reset upstream/gh-pages
  - git add -f \*.html
  - git commit -m "Automatic HTML update via Travis"
  - git push -q upstream HEAD:gh-pages &>/dev/null;
