language: C
sudo: false

addons:
  apt:
    packages:
      - cabal-install-2.0
      - ghc-8.2.2
    sources:
      - hvr-ghc

cache:
  directories:
    - $HOME/.cabal/
    - $HOME/.ghc/
    - $HOME/.agda/

install:
  - cd travis/
  - ./install_agda.sh

script:
  - cd ../src/
  - agda linear/README.agda
